### PR TITLE
remove version.sbt and add versionScheme setting

### LINKED ISSUE #455: Release process?
@francescopellegrini What is the release process? How do you make a new release?

I tried to create a new GitHub Release (I removed it) to trigger the "release" CI job. It worked but it published the new version as a SNAPSHOT as you can see here: https://github.com/embeddedkafka/embedded-kafka/actions/runs/5631099858/job/15257731028#step:5:181

### PR DESCRIPTION
**Pull request by francescopellegrini**
Closes #455 introducing an automated way of releasing artifacts, i.e. creating releases from GitHub.

If this succeeds I'm going to apply the same changes to embedded-kafka-schema-registry as well.

### CODE REVIEW

**Review by guizmaii — APPROVED** [review]
You probably want to remove the `|| sbt sonatypeReleaseAll` part in the `release.yml`
I'm not sure what it is for tho

**Comment by francescopellegrini** [comment]
> You probably want to remove the `|| sbt sonatypeReleaseAll` part in the `release.yml`. It doesn' exist in sbt-ci-release GHA example: https://github.com/sbt/sbt-ci-release/blob/main/.github/workflows/release.yml I'm not sure what it is for tho

Actually it's mentioned [down here](https://github.com/sbt/sbt-ci-release/blob/main/readme.md#secrets) that we need to also set `CI_SONATYPE_RELEASE` to `sonatypeReleaseAll` to publish cross-building projects.

**Review by guizmaii — APPROVED** [review]

**Comment by francescopellegrini** [comment]
@guizmaii Feel free to create v.3.5.1 release whenever you want. :)

**Comment by guizmaii** [comment]
@francescopellegrini Gogogo! 🙂

Thanks

**Comment by guizmaii** [comment]
I think it worked https://github.com/embeddedkafka/embedded-kafka/actions/runs/5777763346/job/15658297336

Let's wait for the Maven cache to refresh

**Comment by francescopellegrini** [comment]
> I think it worked https://github.com/embeddedkafka/embedded-kafka/actions/runs/5777763346/job/15658297336
> 
> Let's wait for the Maven cache to refresh

It didn't work: [Sonatype publish step failed](https://github.com/embeddedkafka/embedded-kafka/actions/runs/5777763346/job/15658297336#step:5:210). I opened #461 to try to fix this.

Then we should delete both the v3.5.1 release and the related tag and try again.

**Comment by francescopellegrini** [comment]
It worked! Thank you @guizmaii for the nice suggestion, I'll apply it to the other project too.

**Comment by guizmaii** [comment]
@francescopellegrini Thanks for making it concrete 🙂

**Pull request merged**
