### PR TITLE
Cross-compile project to Scala 3

### PR DESCRIPTION
**Pull request by mihaisoloi**
Attempting to resolve: https://github.com/embeddedkafka/embedded-kafka/issues/411

### CODE REVIEW

**Comment by mihaisoloi** [comment]
@francescopellegrini @NeQuissimus would this be ok?

**Comment by guizmaii** [comment]
@mihaisoloi @francescopellegrini @NeQuissimus What is the status of this PR? 
That'd be pretty useful if this lib was also published for Scala3

**Review by francescopellegrini — APPROVED** [review]

**Comment by francescopellegrini** [comment]
v3.4.0.1 should be available soon for Scala3. :)

**Comment by guizmaii** [comment]
Thanks @francescopellegrini 🙏 

And thanks for this work @mihaisoloi ❤️

**Pull request merged**
