### PR TITLE
Embedded Kafka Connect server

### PR DESCRIPTION
**Pull request by mmolimar**
Added support for an embedded Kafka Connect server in the library.

Also, there some tests included.

### CODE REVIEW

**Comment by francescopellegrini** [comment]
Hi @mmolimar, thank you so much for the effort!
When I did the same for the Confluent Schema Registry, @manub suggest not to include it in the main library, but to create a [separate project](https://github.com/embeddedkafka/embedded-kafka-schema-registry) instead, so that only those in need for the new server could use it; also this way the original library would not grow unnecessarily in size for everyone.

@NeQuissimus penny for your thoughts. ;)

**Comment by NeQuissimus** [comment]
I vote for a separate project as well. The code looks good to me though!
Admittedly, I do not know very much about Kafka Connect...

**Comment by mmolimar** [comment]
Hi!
Thanks for your comments.

I'd say it makes sense to have it in the same repository. I mean, it's just a new feature in the library taking into account that Kafka Connect is inside the Kafka project (not too much extra libs). You could run in your tests just Kafka or Kafka + Connect based on your needs and obviously using the proper Kafka version which is the same. It's not too much code and you'd have in the same lib a complete suite of embedded servers to test all Kafka related things.

Regarding the Schema Registry, I understand that you actually use the Confluent version (not AK itself) and, in this case, you wouldn't use Kafka Connect (from AK). What I'd do in this case would be the same thing but using the Kafka Connect from Confluent dist and adding Kafka + SR + Connect (but that would be another PR in the other repo).

What do you think?

**Comment by francescopellegrini** [comment]
It could reside in the same repository indeed, but as an independent module, with its own dependencies and tests. The library should accomodate such an extension without the need to alter the original classes, in the same fashion of the Schema Registry project.

**Comment by mmolimar** [comment]
Closing this PR in favour of #222

**Pull request closed without merging**
